name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Step 3: Install dependencies using Makefile
    - name: Install dependencies
      run: |
        cd Project
        make init

    # Step 4: Run tests using Makefile
    - name: Run tests
      run: |
        cd Project
        make test

    # Step 5: Build Docker image using Makefile
    - name: Build Docker image
      run: |
        cd Project
        make build