name: Build and deploy Python app to Azure Web App - Python-DevOps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies using Makefile
      - name: Install dependencies using Makefile
        run: |
          cd Project
          make init

      # Step 4: Run tests using Makefile
      - name: Run tests using Makefile
        run: |
          cd Project
          make test

      # Step 5: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          cd Project
          zip -r ../release.zip ./*

      # Step 6: Upload the artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D19538E91D684761943656081A49B475 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_926FF673B1C84B45831896014FD828AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8C11D0180E79415EA8748D2DDA6FBDF3 }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'math-app'  # Replace with your actual Azure Web App name
          slot-name: 'Production'
